- roms/ports/Switch Updater.sh
Fix small mistake that went unnoticed
> Update Switch Updater.sh

- system/switch/extra/batocera-switch-updater.sh
+ redirect batoceraswit.ch/ dependencies downloads to gh ordo main branch
+ general script cleanup
>  batocera-switch-updater patch2

- system/.local/share/applications/ryujinx-avalonia-config.desktop
- system/.local/share/applications/ryujinx-config.desktop
- system/.local/share/applications/yuzu-config.desktop
- system/.local/share/applications/yuzuEA-config.desktop
redundant due to latest updater patch &/or bato changes
> Delete system/.local/share/applications directory

- system/switch/extra/batocera-switch-updater.sh
fixed no display for updater upon case reported by user @ bn dc
> + updater fix

- system/switch/extra/batocera-switch-updater.sh
> +updaterfix

- system/switch/extra/batocera-switch-installer.sh
- system/switch/extra/batocera-switch-updater.sh
adding batocera-switch-installer.sh to link it through: 
curl -L batoceraswit.ch | bash
> +batocera-switch-installer.sh

- system/switch/extra/batocera-switch-updater.sh
+ fixed empty lines for startup generator
> startup cleanups

- system/switch/extra/batocera-switch-updater.sh
+ added switchlauncher.py and GeneratorImporter.py to updated files
> + pulling new files

- system/switch/extra/batocera-switch-sshupdater.sh
+ allowing latest ryujinx builds for sshupdater
> + allowing latest ryujinx builds for sshupdater

- system/switch/extra/batocera-switch-installer.sh
- system/switch/extra/batocera-switch-sshupdater.sh
+ firmware linker for sshupdater 
+ paths filled for installer
> + firmware linker for sshupdater + paths filled for installer

- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
> +yuzupuller@updater+ssh

- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
++ryujinxLDN
@
/userdata/system/switch/Ryujinx-LDN.AppImage
> ++ryujinxLDN

- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
> +es_systems.cfg@updaters

- system/switch/extra/batocera-switch-installer.sh
- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
+restore xterm_fontcolor after install and/or update 
+remove_oldupdaters during install and/or update
> +restore xterm_fontcolor  &  +remove_oldupdaters

- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
+fixing_firmware_linker in updater & sshupdater
> +fixing_firmware_linker

- system/configs/evmapy/switch.keys
- system/switch/extra/batocera-switch-updater.sh
+silent killall in keys to not spam logs
> +redo_fw_link

- system/switch/extra/batocera-switch-installer.sh
> intaller fix

- roms/ports/Switch Updater.sh.keys
- system/switch/extra/batocera-switch-updater.sh
in the odd case the udpater borks; hotkey+start = killall -9 xterm & killall -9 emulationstation
> add Switch Updater.sh.keys and autodownload in updater

- system/switch/extra/batocera-switch-updater.sh
+ major revamp
+ updated display/textsize function
+ rewrote ui/info to be cleaner
+ rewrote tasks to run more background (=faster)
+ added loading animation, better ux (+background)
+ added config options (unlock ryu udpates, ! use animation)
+ batocera-switch-updater.sh can now be used as standalone,
customizable port etc
> updater v3.0 + animation

- system/switch/extra/batocera-switch-updater.sh
+ the startup-line will now integrate into the very beginning of custom.sh thus eliminating any risk of bork if user content,casesesacs, etc are present
+ fix to patcher.sh
> rework @ startup scripts

- roms/ports/Switch Updater.sh
- system/switch/extra/batocera-switch-updater.sh
run updater only if net is available, otherwise show 'no connection' info
> add connection check

- roms/ports/Switch Updater.sh
- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
+ lesscached downloads for wget
> sshupdater bump

- system/switch/extra/batocera-switch-installer.sh
- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
+ change netcheck from ping to curl httpreq
> + change netcheck from ping to curl httpreq

- system/switch/extra/batocera-switch-installer.sh
- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-sync-firmware.sh
- system/switch/extra/batocera-switch-updater.sh
+ now syncs fw on each emulator launch, making fw changes immediately available across emus&folders
> + revamped firmware sync

- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
+ enable ryujinx gui controller config
> + enable ryujinx gui controller config 

- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
+ryujinx/guicontroller fixes for v35+v36
> +ryujinx/guicontroller fixes for v35+v36

- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
+ryujinx/guicontroller fixes for v35/v36
> +ryujinx/guicontroller fixes for v35/v36

- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
- system/switch/extra/ryujinx-controller-patcher.sh
+ryujinx-controller-patcher.sh
> +ryujinx-controller-patcher.sh

- system/configs/evmapy/switch.keys
> +fix hide mouse on exit

- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
> +increase filelimits

- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
> +increase openfile limits

- system/switch/configgen/switchlauncher.py
+fix for python3.11 @ v37
@foclabroc @ordovice
> +fix for python3.11 @ v37

- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
> v37 compat fixes

- system/switch/configgen/switchlauncher.py
v37 compat fixes to switchlauncher.py
> v37 compat fixes to switchlauncher.py

- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
- system/switch/extra/yuzu-controller-patcher.sh
+ v37 yuzu-controller-patcher.sh
> + v37 yuzu-controller-patcher.sh 

- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
+lock yuzu/ea@3333/1321 for v35
> +lock yuzu/ea@3333/1321 for v35

- system/switch/extra/batocera-switch-sshupdater.sh
- system/switch/extra/batocera-switch-updater.sh
+ryujinx gui controller config fix
> +ryujinx gui controller config fix

- system/switch/extra/batocera-switch-installer.sh
+general cleanups additions and fixes
> +general cleanups additions and fixes

- system/switch/extra/batocera-switch-updater.sh
> +updater fixes

- system/configs/emulationstation/es_features_switch.cfg
- system/switch/configgen/generators/ryujinx/ryujinxMainlineGenerator.py
Use OpenGl instead
see https://github.com/Ryujinx/Ryujinx/blob/master/src/Ryujinx.Common/Configuration/GraphicsBackend.cs#L10
> OpenGL is not valid for Ryujinx and so it resets to Vulkan

- system/switch/extra/batocera-switch-config.txt
- system/switch/extra/batocera-switch-installer.sh
- system/switch/extra/batocera-switch-updater.sh
++ users can now easily pick: 
> which emulators to update
> specific emulator versions for yuzu, yuzuea, ryu, ava
> text/theme colors & fontsize for updater window
> ++config file for updater = ~/switch/CONFIG.txt

- system/switch/extra/batocera-switch-config.txt
- system/switch/extra/batocera-switch-installer.sh
- system/switch/extra/batocera-switch-updater.sh
syntax changes to make it clearer what's up
> + config.txt changes to allow unlocks on v<37

- system/switch/extra/batocera-switch-config.txt
syntax changes to make it clearer what's up
``` 
USE_YUZU_VERSION=AUTO
USE_YUZUEA_VERSION=AUTO
USE_RYUJINX_VERSION=1.1.382
USE_RYUJINXAVALONIA_VERSION=1.1.382
#---------------------------------------------------------------
#---------------------------------------------------------------
#
#
#
#---------------------------------------------------------------
#
#
#
#
#---------------------------------------------------------------
```
> + CONFIG.txt fixes 

- system/switch/extra/batocera-switch-config.txt
```
USE_YUZU_VERSION=AUTO
USE_YUZUEA_VERSION=AUTO
USE_RYUJINX_VERSION=1.1.382
USE_RYUJINXAVALONIA_VERSION=1.1.382
#---------------------------------------------------------------
#
#
#---------------------------------------------------------------
#
#
#---------------------------------------------------------------
#
#
#
#
#---------------------------------------------------------------
#
#
#---------------------------------------------------------------
```
> + CONFIG.txt fixes

- system/switch/extra/batocera-switch-nsz-converter.sh
v37 fixes for nsz-converter + cleanups
> v37 fixes for nsz-converter

- system/switch/extra/batocera-switch-updater.sh
+pull entire configgen/sdl2 in updater
> +pull entire configgen/sdl2 in updater

- system/switch/extra/batocera-switch-updater.sh
> +updated sdl for custom 382

- system/switch/extra/batocera-switch-updater.sh
+updated sdl for custom 382 +ldn2notava
> +updated sdl for custom 382 +ldn2notava

- system/switch/extra/batocera-switch-updater.sh
+disabled inapp autoupdates for ryus
> +disabled inapp autoupdates for ryus

- system/switch/extra/batocera-switch-updater.sh
Makes it so yuzu is a bring your own app image system. Also adds m5d checks for latest versions of yuzu/EA for added security.
> switch-updater-fix

- system/configs/emulationstation/es_features_switch.cfg
> Update es_features_switch.cfg add videomode
